/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

(* top =  1  *)
(* src = "hierarchical_synth.v:3.1-23.10" *)
module multiple_modules(a, b, c, y);
  (* src = "hierarchical_synth.v:4.9-4.10" *)
  input a;
  wire a;
  (* src = "hierarchical_synth.v:6.9-6.10" *)
  input b;
  wire b;
  (* src = "hierarchical_synth.v:8.9-8.10" *)
  input c;
  wire c;
  (* src = "hierarchical_synth.v:10.8-10.12" *)
  wire net1;
  (* hdlname = "u1 _0_" *)
  (* src = "hierarchical_synth.v:26.8-26.11" *)
  wire \u1._0_ ;
  (* hdlname = "u1 _1_" *)
  (* src = "hierarchical_synth.v:27.8-27.11" *)
  wire \u1._1_ ;
  (* hdlname = "u1 _2_" *)
  (* src = "hierarchical_synth.v:28.8-28.11" *)
  wire \u1._2_ ;
  (* hdlname = "u1 a" *)
  (* src = "hierarchical_synth.v:29.9-29.10" *)
  wire \u1.a ;
  (* hdlname = "u1 b" *)
  (* src = "hierarchical_synth.v:31.9-31.10" *)
  wire \u1.b ;
  (* hdlname = "u1 y" *)
  (* src = "hierarchical_synth.v:33.10-33.11" *)
  wire \u1.y ;
  (* hdlname = "u2 _0_" *)
  (* src = "hierarchical_synth.v:46.8-46.11" *)
  wire \u2._0_ ;
  (* hdlname = "u2 _1_" *)
  (* src = "hierarchical_synth.v:47.8-47.11" *)
  wire \u2._1_ ;
  (* hdlname = "u2 _2_" *)
  (* src = "hierarchical_synth.v:48.8-48.11" *)
  wire \u2._2_ ;
  (* hdlname = "u2 a" *)
  (* src = "hierarchical_synth.v:49.9-49.10" *)
  wire \u2.a ;
  (* hdlname = "u2 b" *)
  (* src = "hierarchical_synth.v:51.9-51.10" *)
  wire \u2.b ;
  (* hdlname = "u2 y" *)
  (* src = "hierarchical_synth.v:53.10-53.11" *)
  wire \u2.y ;
  (* src = "hierarchical_synth.v:11.10-11.11" *)
  output y;
  wire y;
  (* hdlname = "u1 _3_" *)
  (* module_not_derived = 32'd1 *)
  (* src = "hierarchical_synth.v:35.27-39.4" *)
  sky130_fd_sc_hd__and2_0 \u1._3_  (
    .A(b),
    .B(a),
    .X(\u1._2_ )
  );
  (* hdlname = "u2 _3_" *)
  (* module_not_derived = 32'd1 *)
  (* src = "hierarchical_synth.v:55.26-59.4" *)
  sky130_fd_sc_hd__or2_0 \u2._3_  (
    .A(c),
    .B(\u1._2_ ),
    .X(\u2._2_ )
  );
  assign \u2._0_  = \u1._2_ ;
  assign \u2._1_  = c;
  assign \u2.a  = \u1._2_ ;
  assign \u2.b  = c;
  assign \u2.y  = \u2._2_ ;
  assign \u1._0_  = a;
  assign \u1._1_  = b;
  assign \u1.a  = a;
  assign \u1.b  = b;
  assign \u1.y  = \u1._2_ ;
  assign y = \u2._2_ ;
  assign net1 = \u1._2_ ;
endmodule
