/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module multiple_modules(a, b, c, y);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  wire net1;
  wire \u1._2_ ;
  wire \u1.a ;
  wire \u1.b ;
  wire \u1.y ;
  wire \u2._2_ ;
  wire \u2.a ;
  wire \u2.b ;
  wire \u2.y ;
  output y;
  wire y;
  sky130_fd_sc_hd__and2_0 \u1._3_  (
    .A(b),
    .B(a),
    .X(\u1._2_ )
  );
  sky130_fd_sc_hd__or2_0 \u2._3_  (
    .A(c),
    .B(\u1._2_ ),
    .X(\u2._2_ )
  );
  assign net1 = \u1._2_ ;
  assign \u1.a  = a;
  assign \u1.b  = b;
  assign \u1.y  = \u1._2_ ;
  assign \u2.a  = \u1._2_ ;
  assign \u2.b  = c;
  assign \u2.y  = \u2._2_ ;
  assign y = \u2._2_ ;
endmodule
