/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

(* top =  1  *)
(* src = "good_counter.v:1.1-21.10" *)
module good_counter(clk, reset, cnt);
  (* src = "good_counter.v:11.1-19.4" *)
  wire [1:0] _0_;
  (* src = "good_counter.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "good_counter.v:4.22-4.25" *)
  output [1:0] cnt;
  reg [1:0] cnt;
  (* src = "good_counter.v:3.11-3.16" *)
  input reset;
  wire reset;
  assign _0_[0] = ~(cnt[1] | cnt[0]);
  assign _0_[1] = cnt[0] & ~(cnt[1]);
  (* src = "good_counter.v:11.1-19.4" *)
  always @(posedge clk, posedge reset)
    if (reset) cnt[0] <= 1'h0;
    else cnt[0] <= _0_[0];
  (* src = "good_counter.v:11.1-19.4" *)
  always @(posedge clk, posedge reset)
    if (reset) cnt[1] <= 1'h0;
    else cnt[1] <= _0_[1];
endmodule
